version: 2.1

orbs:
  clojure: hannah/clojure@dev:test

jobs:
  test:
    executor:
      name: clojure/generic_exec
      wd: /root/lacinia
      docker_image: clojure:lein-2.7.1
    steps:
      - clojure/cached_test:
         pre_test_steps:
           - restore_cache:
               keys:
               - &cache_key v1-dependency-jars-{{ checksum "project.clj" }}
               - v1-dependency-jars
         test_str: lein deps # Not a test string... but orb expects a test string here
         save_key: *cache_key
         save_path: /root/.m2
      - run:
          command: lein test2junit
      - store_test_results:
          path: /root/lacinia/target/test2junit

workflows:
  test:
    jobs:
    - test
